export const titles = [
  "Dr",
  "Mr",
  "Mrs",
  "Miss",
  "Ms",
  "Prof",
  "Mx",
  "M",
  "Pr",
  "N/A",
];

export const positions = [
  "Associate",
  "Dental Assistant",
  "Dental Hygienist",
  "Dental Nurse",
  "Dental Practice Manager",
  "Dental Technician",
  "Dentist",
  "Endodontist",
  "Founder",
  "Lab",
  "Manager",
  "Oral and Maxillofacial Surgeon",
  "Oral Surgeon",
  "Orthodontist",
  "Paediatric Dentist",
  "Periodontist",
  "Principal Dentist",
  "Prosthodontist",
  "Receptionist",
  "Specialist",
  "Student",
  "Therapist",
  "TCO (Treatment Coordinator)",
  "Other",
];
